//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAMK.ICT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LekaEntities : DbContext
    {
        public LekaEntities()
            : base("name=LekaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<asiakas> asiakkaat { get; set; }
        public DbSet<kategoria> kategoriat { get; set; }
        public DbSet<paketti> paketit { get; set; }
        public DbSet<tilaus> tilaukset { get; set; }
        public DbSet<tilaus_tuote> tilaus_tuotteet { get; set; }
        public DbSet<tuote> tuotteet { get; set; }
        public DbSet<user> users { get; set; }
    }
}
