//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAMK.ICT
{
    using System;
    using System.Collections.Generic;
    
    public partial class paketti
    {
        public paketti()
        {
            this.tuote = new HashSet<tuote>();
        }
    
        public int huoneID { get; set; }
        public double paketinHinta { get; set; }
        public string nimi { get; set; }
        public int pakettiID { get; set; }
        public string pakettiKuvaus { get; set; }
    
        public virtual ICollection<tuote> tuote { get; set; }
    }
}
