//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAMK.ICT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tilaus_tuote
    {
        public int tilaus_idtilaus { get; set; }
        public int tuote_idtuote { get; set; }
        public Nullable<decimal> tuotehinta { get; set; }
        public Nullable<int> tuotelkm { get; set; }
    
        public virtual tilaus tilaus { get; set; }
        public virtual tuote tuote { get; set; }
    }
}
