//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAMK.ICT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tilaus
    {
        public tilaus()
        {
            this.tilaus_has_tuote = new HashSet<tilaus_tuote>();
        }
    
        public int idtilaus { get; set; }
        public int asiakas_idasiakas { get; set; }
    
        public virtual asiakas asiakas { get; set; }
        public virtual ICollection<tilaus_tuote> tilaus_has_tuote { get; set; }
    }
}
