//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAMK.ICT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuote
    {
        public tuote()
        {
            this.tilaus_has_tuote = new HashSet<tilaus_tuote>();
            this.paketti = new HashSet<paketti>();
            this.kategoria = new HashSet<kategoria>();
        }
    
        public int idtuote { get; set; }
        public string tuotenimi { get; set; }
        public string kuvaus { get; set; }
        public Nullable<double> hinta { get; set; }
    
        public virtual ICollection<tilaus_tuote> tilaus_has_tuote { get; set; }
        public virtual ICollection<paketti> paketti { get; set; }
        public virtual ICollection<kategoria> kategoria { get; set; }
    }
}
